Implementing getAll() for GoogleTasksDataAccessObject
nnzahin/Brainsweep pull request #34
Opened 2023-12-02 21:26 UTC by nnzahin

2023-12-02 22:02 UTC, thatlittlegit requested changes
Thanks for working on it! Main issue is that the `idsToUUIDs` probably won't work, see the comment I left. Otherwise, I have a handful of other minor issues with it, as mentioned.

Also, _if_ it wouldn't be too much hassle, would you mind writing a few test cases? I think I have some in TaskAccount which could be used as inspiration; the idea is to use a constant APIProvider and see how it handles the responses.

Again, though, thanks for working on it! We can't be that far from having search working now :D

2023-12-02 22:44 UTC, nnzahin commented on src/main/java/somethingrandom/dataaccess/google/tasks/TaskList.java
> +            JsonItemFactory factory = new JsonItemFactory();
Static should be ok

2023-12-02 22:52 UTC, thatlittlegit commented on src/main/java/somethingrandom/dataaccess/google/tasks/TaskList.java
> +            JSONObject jsonItem = new JSONObject(item);
Should've pointed this out the first time: I don't think this is right. The [documentation](https://stleary.github.io/JSON-java/org/json/JSONObject.html) says:

> [JSONObject](https://stleary.github.io/JSON-java/org/json/JSONObject.html#JSONObject-java.lang.Object-)([Object](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html?is-external=true) bean)
Construct a JSONObject from an Object using bean getters.

But JSONObject isn't a bean. Probably `(JSONObject) item` would work?

2023-12-03 01:00 UTC, thatlittlegit approved these changes
Some tests would be nice in future, but looks good!

2023-12-03 01:15 UTC, fahimfa3 commented on src/main/java/somethingrandom/dataaccess/google/tasks/GoogleTasksDataAccessObject.java
> +    public Collection<Item> getAll() {
Can you rename this to getAllItems()? That's the name in the Search Data Access Interface

2023-12-03 01:25 UTC, merged